apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cf-jameskrdev
  namespace: critical
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: external-dns-cf-jameskrdev
  data:
  - secretKey: CF_API_TOKEN
    remoteRef:
      key: KV.NanoNetwork/cloudflare
      property: token-dns

