---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cf-jameskrdev
  namespace: critical
spec:
  interval: 30m
  timeout: 2m
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    policy: sync
    provider:
      name: cloudflare
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["jameskr.dev"]
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external
    env:
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cf-jameskrdev
            key: *name
