---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-secrets
  namespace: critical
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
