apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: critical
spec:
  interval: 30m
  timeout: 2m
  path: "./clusters/home/apps/critical/external-secrets/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: critical
