apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cloudflared
  namespace: critical

spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: norton-vault-store
    kind: ClusterSecretStore  # or ClusterSecretStore
  target:
    deletionPolicy: Delete
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /KV.NanoNetwork/data/cloudflared
