apiVersion: v1
kind: Secret
metadata:
    name: hcvault-secret
    namespace: critical
type: Opaque
data:
    vault-token: ENC[AES256_GCM,data:xU7dz5DTYtFzNqzBrhjZ3mgMzX83awXsWA/kejvNAndxxsx9gadXKA==,iv:hMgmhAdYFqz2exdipY6NmS/SCDQ/Hr7EV1aFzdM7xPE=,tag:bnDpGxeeOC4lZ6XDCp8swg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr9g4wd74psccuuq2dsunw94d0t7nxdm7jzuxj924m0h44cmmf6svuq5lh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWai9VaUgvUHkwa3kyZUQv
            OWdmVXRHQWo5cFh5bnRGVTRJTVVxZnNjeXdjCjJyd3RnZGMrNkV2ZW90TFBPT0JV
            d3VKc1dQS0o4NmdPdnYrcjhSSHVUMUUKLS0tIEpvNTA1ZjV6ZndqNExJVGE1M0g0
            N3pmc2RsN0tjVnhrQzBBbXBhRGd0YWMKRiFs+1SZvAgKtlq/JFZSafsfTq/2pCpD
            N2tcS+yxk8oX3/+0zyT+NOQ4yNdO0m7+/yCNypu6rk2zgfbk5EqnNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T00:15:33Z"
    mac: ENC[AES256_GCM,data:qhvFx1XXOGdbtw+oEkQmJf4p9QswGCfd/KYzQ9mqgVmkqS8It/pNkMi3ENwg/pbACZPsP0HzkqB/RtMiHUK0kWYNKa4ctw1S7/In5YC/MCosX2+CiOgd6d/llyTCOaH8pxnNAJ5hWW8mviTXS4d/yJgMT+s8oWOumU9sBmlAOaI=,iv:D6fFrzDEcSwFeL9MjWimoCo5WUDlNxJcs2Y1ndXMsIc=,tag:EXRkZdSK+Pf0h8lSledK0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
