apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crashserver-secrets
  namespace: crashserver
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: crashserver-secrets
  data:
  # Database
  - secretKey: CRASH_DB__db
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: database
  - secretKey: CRASH_DB__user
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: username
  - secretKey: CRASH_DB__passwd
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: password
  - secretKey: CRASH_DB__host
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: host

  # Redis
  - secretKey: CRASH_REDIS__host
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: host
  - secretKey: CRASH_REDIS__passwd
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: redis_password

  # S3 Store
  - secretKey: CRASH_S3STORE__BUCKET_NAME
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: s3_bucket_name
  - secretKey: CRASH_S3STORE__ACCESS_KEY
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: password
  - secretKey: CRASH_S3STORE__SECRET_KEY
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: s3_secret_key
  - secretKey: CRASH_S3STORE__ENDPOINT_URL
    remoteRef:
      key: KV.NanoNetwork/crashserver
      property: s3_endpoint_url
