---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crashserver-worker
  namespace: crashserver
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      crashserver-worker:
        replicas: 3
        containers:
          app:
            image:
              repository: ghcr.io/jameskr97/crashserver
              tag: latest
            command: ["python3", "/app/main-rq.py"]
            envFrom:
              - secretRef:
                  name: crashserver-secrets
            securityContext:
              allowPrivilegeEscalation: true
            resources:
              requests:
                cpu: 250m
              limits:
                memory: 2Gi
    persistence:
      logs:
        type: emptyDir
        globalMounts:
          - path: /logs
      storage:
        type: emptyDir
        globalMounts:
          - path: /storage
