apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-secret
  namespace: coder
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: coder-secret
  data:
  # Database
  - secretKey: username
    remoteRef:
      key: KV.NanoNetwork/coder
      property: username
  - secretKey: password
    remoteRef:
      key: KV.NanoNetwork/coder
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-app-secret
  namespace: coder
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: coder-app-secret
  data:
  - secretKey: CODER_PG_CONNECTION_URL
    remoteRef:
      key: KV.NanoNetwork/coder
      property: url
  - secretKey: CODER_OIDC_ISSUER_URL
    remoteRef:
      key: KV.NanoNetwork/coder
      property: oidc_issuer_url
  - secretKey: CODER_OIDC_EMAIL_DOMAIN
    remoteRef:
      key: KV.NanoNetwork/coder
      property: oidc_email_domain
  - secretKey: CODER_OIDC_CLIENT_ID
    remoteRef:
      key: KV.NanoNetwork/coder
      property: oidc_client_id
  - secretKey: CODER_OIDC_CLIENT_SECRET
    remoteRef:
      key: KV.NanoNetwork/coder
      property: oidc_client_secret
