---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  values:
    coder:
      envFrom:
        - secretRef:
            name: coder-app-secret
      tls:
        secretName: coder-tls
      certs:
        secrets:
          - name: nanonetwork-ca-bundle
            key: ca.crt
      service:
        type: ClusterIP
      ingress:
        enable: true
        className: nginx
        host: coder.jameskr.dev
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        tls:
          enable: true
          secretName: coder-tls

