apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fusionauth-secret
  namespace: support
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: fusionauth-creds
  data:
  - secretKey: password
    remoteRef:
      key: KV.NanoNetwork/fusionauth
      property: database_password

