# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app network-jameskr.dev-externaldns
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/norton/apps/network/jameskr.dev/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-norton
  wait: true
  interval: 1m
  timeout: 1m
