---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app trust-manager
  namespace: critical
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    secretTargets:
      enabled: true
      authorizedSecrets: [nanonetwork-ca-bundle]
    app:
      trust:
        namespace: critical
      webhook:
        tls:
          helmCert:
            enabled: true
