apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
  namespace: critical
spec:
  interval: 30m
  timeout: 2m
  path: "./clusters/home/apps/critical/trust-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: trust-manager
      namespace: critical
