---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jameskr-dev
  namespace: network
spec:
  secretName: jameskr-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: jameskr.dev
  dnsNames: ["jameskr.dev", "*.jameskr.dev"]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: norton-jameskr-dev
  namespace: network
spec:
  secretName: norton-jameskr-dev-tls
  issuerRef:
    name: norton-vault
    kind: ClusterIssuer
  commonName: norton.jameskr.dev
  dnsNames: ["norton.jameskr.dev", "*.norton.jameskr.dev"]
