---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-manager
  namespace: critical
spec:
  interval: 1h
  timeout: 2m
  chart:
    spec:
      chart: *app
      version: 1.15.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    dns01RecursiveNameservers: 1.1.1.1:53
    dns01RecursiveNameserversOnly: true
