---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fusionauth.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
