apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: personal
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: mealie-secrets
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: KV.NanoNetwork/mealie
      property: postgres_password
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: KV.NanoNetwork/mealie
      property: oidc_client_secret
  - secretKey: LDAP_QUERY_BIND
    remoteRef:
      key: KV.NanoNetwork/lldap
      property: bind_user
  - secretKey: LDAP_QUERY_PASSWORD
    remoteRef:
      key: KV.NanoNetwork/lldap
      property: bind_password
