apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secret-store
  namespace: critical
spec:
  dependsOn:
    - name: external-secrets
  timeout: 1m
  interval: 30s
  path: "./clusters/home/apps/critical/external-secrets/stores"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: flux-system
