apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
  namespace: critical
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: cloudflare-secret
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: KV.NanoNetwork/cloudflare
      property: token-dns
