---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-issuers
  namespace: critical
spec:
  dependsOn:
    - name: cert-manager
    - name: external-secret-store
  path: ./clusters/home/apps/critical/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
