apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: critical
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: norton-vault-store
  target:
    name: external-dns-secret
  data:
  - secretKey: external-dns-password
    remoteRef:
      key: LDAP.ExternalDNS/auth
      property: password
